#!/usr/bin/env node

'use strict'

var eccrypto = require('eccrypto')

var [
  command, 
  script, 
  public_key, 
  message
] = process.argv

if (!(public_key && message)) {
  process.stdout.write(JSON.stringify({
    error: 'public key or message not given'
  }))
  process.exit(1)
}

var pk, m

try {
  pk = Buffer.from(public_key, 'hex')
  m = Buffer.from(message, 'hex')
} catch (err) {
  process.stdout.write(JSON.stringify({
    error: 'public key or message is not a hexadecimal string'
  }))
  process.exit(1)
}

eccrypto.encrypt(pk, m).then(function(encrypted) {
  process.stdout.write(JSON.stringify(encrypted))
  process.exit(0)
}).catch(function(err) {
  process.stdout.write(JSON.stringify({
    eccrypto_error: JSON.stringify(err)
  }))
  process.exit(1)
})
