#!/usr/bin/env node

'use strict'

var crypto = require('crypto')
var eccrypto = require('eccrypto')

var public_key = crypto.randomBytes(32).toString('hex')
var private_key = eccrypto.getPublic(public_key).toString('hex')

process.stdout.write(JSON.stringify({
  public_key: public_key,
  private_key: private_key
}))

process.exit(0)
