#!/usr/bin/env node

'use strict'

var crypto = require('crypto')
var eccrypto = require('eccrypto')

var private_key = crypto.randomBytes(32)
var public_key = eccrypto.getPublic(private_key)

process.stdout.write(JSON.stringify({
  public_key: public_key.toString('hex'),
  private_key: private_key.toString('hex')
}))

process.exit(0)
