#!/usr/bin/env node

'use strict'

var eccrypto = require('eccrypto')

var [
  command,
  script,
  private_key,
  message
] = process.argv

if (!(private_key && message)) {
  process.stdout.write(JSON.stringify({
    error: 'private key or message not given'
  }))
  process.exit(1)
}

var pk, m

try {
  pk = Buffer.from(private_key, 'hex')
  m = Buffer.from(message, 'hex')
} catch (err) {
  process.stdout.write(JSON.stringify({
    error: 'private key and/or message is not a hexadecimal string'
  }))
  process.exit(1)
}

eccrypto.sign(pk, m).then(function(signature) {
  process.stdout.write(JSON.stringify({signature: signature}))
  process.exit(0)
}).catch(function(err) {
  process.stdout.write(JSON.stringify({
    error: 'signature creation failed', 
    eccrypto_error: JSON.stringify(err || true)}
  ))
  process.exit(1)
})
